/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.projetbd.Projet;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF/iOL0dOKyaoE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF/iOL0dOKyaoE= >>
// ----------- >>
public class DefinitionStation {
    // ----------- << attribute.annotations@AAAAAAF/iORvXeQ83sU= >>
    // ----------- >>
    private Integer heure;

    // ----------- << attribute.annotations@AAAAAAF/iOYVpuZgUGA= >>
    // ----------- >>
    private Definition defStation;

    // ----------- << attribute.annotations@AAAAAAF/iOb3VusGYNI= >>
    // ----------- >>
    private Station station;

    public Integer getHeure() {
        return heure;
    }

    public Definition getDefStation() {
        return defStation;
    }

    public Station getStation() {
        return station;
    }

    public DefinitionStation setHeure(Integer heure) {
        this.heure = heure;
        return this;
    }

    public DefinitionStation setDefStation(Definition defStation) {
        this.defStation = defStation;
        return this;
    }

    public DefinitionStation setStation(Station station) {
        this.station = station;
        return this;
    }

    public DefinitionStation linkStation(Station _station) {
        if (_station != null) {
            _station.getDefinitions().add(this);
        }

        unlinkStation();
        setStation(_station);
        return this;
    }

    public DefinitionStation unlinkStation() {
        if (getStation() != null) {
            getStation().getDefinitions().remove(this);
            setStation(null);
        }
        return this;
    }

// ----------- << class.extras@AAAAAAF/iOL0dOKyaoE= >>
// ----------- >>
}