/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.projetbd.Projet;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF/ZIAg/BDqHao= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF/ZIAg/BDqHao= >>
// ----------- >>
public class Modele {
    // ----------- << attribute.annotations@AAAAAAF/ZID/LBH8r4g= >>
    // ----------- >>
    private String nom;

    // ----------- << attribute.annotations@AAAAAAF/ZIFo5hJ2KSQ= >>
    // ----------- >>
    private Float coutHoraire;

    // ----------- << attribute.annotations@AAAAAAF/ZII+jBMLrdo= >>
    // ----------- >>
    private Set<Velo> velos = new HashSet<>();

    private String getNom() {
        return nom;
    }

    private Float getCoutHoraire() {
        return coutHoraire;
    }

    public Set<Velo> getVelos() {
        return velos;
    }

    private Modele setNom(String nom) {
        this.nom = nom;
        return this;
    }

    private Modele setCoutHoraire(Float coutHoraire) {
        this.coutHoraire = coutHoraire;
        return this;
    }

    public Modele linkVelos(Velo _velos) {
        if (_velos != null) {
            _velos.unlinkModele();
            _velos.setModele(this);
            getVelos().add(_velos);
        }
        return this;
    }

    public Modele unlinkVelos(Velo _velos) {
        if (_velos != null) {
            _velos.setModele(null);
            getVelos().remove(_velos);
        }
        return this;
    }

    public Modele unlinkVelos(Velo _velos, Iterator<Velo> it) {
        if (_velos != null) {
            _velos.setModele(null);
            it.remove();
        }
        return this;
    }

// ----------- << class.extras@AAAAAAF/ZIAg/BDqHao= >>
// ----------- >>
}