/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.projetbd.Projet;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF/ZGoZ4AOAc1M= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF/ZGoZ4AOAc1M= >>
// ----------- >>
public class Velo {
    // ----------- << attribute.annotations@AAAAAAF/ZGqpGgOxm4c= >>
    // ----------- >>
    private Date dateMiseService;

    // ----------- << attribute.annotations@AAAAAAF/ZGr70gO51ec= >>
    // ----------- >>
    private Etat etat;

    // ----------- << attribute.annotations@AAAAAAF/ZH4F5w3cVT4= >>
    // ----------- >>
    private String puce;

    // ----------- << attribute.annotations@AAAAAAF/ZHFw1QVcl+o= >>
    // ----------- >>
    private Bornette bornette;

    // ----------- << attribute.annotations@AAAAAAF/ZII+jBMMJks= >>
    // ----------- >>
    private Modele modele;

    // ----------- << attribute.annotations@AAAAAAF/iNGpv6nDB00= >>
    // ----------- >>
    private Set<Trajet> trajets = new HashSet<>();

    private Date getDateMiseService() {
        return dateMiseService;
    }

    private Etat getEtat() {
        return etat;
    }

    private String getPuce() {
        return puce;
    }

    public Bornette getBornette() {
        return bornette;
    }

    public Modele getModele() {
        return modele;
    }

    public Set<Trajet> getTrajets() {
        return trajets;
    }

    private Velo setDateMiseService(Date dateMiseService) {
        this.dateMiseService = dateMiseService;
        return this;
    }

    private Velo setEtat(Etat etat) {
        this.etat = etat;
        return this;
    }

    private Velo setPuce(String puce) {
        this.puce = puce;
        return this;
    }

    public Velo setBornette(Bornette bornette) {
        this.bornette = bornette;
        return this;
    }

    public Velo setModele(Modele modele) {
        this.modele = modele;
        return this;
    }

    public Velo linkBornette(Bornette _bornette) {
        if (_bornette != null) {
            _bornette.unlinkVelo();
            _bornette.setVelo(this);
        }

        unlinkBornette();
        setBornette(_bornette);
        return this;
    }

    public Velo linkModele(Modele _modele) {
        if (_modele != null) {
            _modele.getVelos().add(this);
        }

        unlinkModele();
        setModele(_modele);
        return this;
    }

    public Velo linkTrajets(Trajet _trajets) {
        if (_trajets != null) {
            _trajets.unlinkVelo();
            _trajets.setVelo(this);
            getTrajets().add(_trajets);
        }
        return this;
    }

    public Velo unlinkBornette() {
        if (getBornette() != null) {
            getBornette().setVelo(null);
            setBornette(null);
        }
        return this;
    }

    public Velo unlinkModele() {
        if (getModele() != null) {
            getModele().getVelos().remove(this);
            setModele(null);
        }
        return this;
    }

    public Velo unlinkTrajets(Trajet _trajets) {
        if (_trajets != null) {
            _trajets.setVelo(null);
            getTrajets().remove(_trajets);
        }
        return this;
    }

    public Velo unlinkTrajets(Trajet _trajets, Iterator<Trajet> it) {
        if (_trajets != null) {
            _trajets.setVelo(null);
            it.remove();
        }
        return this;
    }

// ----------- << class.extras@AAAAAAF/ZGoZ4AOAc1M= >>
// ----------- >>
}