/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF/ZH1uig1SsOU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF/ZH1uig1SsOU= >>
// ----------- >>
public class Abonne extends Client {
    // ----------- << attribute.annotations@AAAAAAF/ZH6B3w5jNx8= >>
    // ----------- >>
    private String nom;

    // ----------- << attribute.annotations@AAAAAAF/ZH6woQ64kV0= >>
    // ----------- >>
    private String prenom;

    // ----------- << attribute.annotations@AAAAAAF/ZH7Cpg7u1XU= >>
    // ----------- >>
    private Date dateN;

    // ----------- << attribute.annotations@AAAAAAF/ZH7SkA8kSas= >>
    // ----------- >>
    private Sexe sexe;

    // ----------- << attribute.annotations@AAAAAAF/ZH9kpw/eB5M= >>
    // ----------- >>
    private String adresse;

    // ----------- << attribute.annotations@AAAAAAF/ZJ5GDx5jne0= >>
    // ----------- >>
    private Date dateDebutAb;

    // ----------- << attribute.annotations@AAAAAAF/ZM7AdUIDk8E= >>
    // ----------- >>
    private Integer creditTemps;

    // ----------- << attribute.annotations@AAAAAAF/ZONRumSpinc= >>
    // ----------- >>
    private Set<Location> locations = new HashSet<>();

    private String getNom() {
        return nom;
    }

    private String getPrenom() {
        return prenom;
    }

    private Date getDateN() {
        return dateN;
    }

    private Sexe getSexe() {
        return sexe;
    }

    private String getAdresse() {
        return adresse;
    }

    private Date getDateDebutAb() {
        return dateDebutAb;
    }

    private Integer getCreditTemps() {
        return creditTemps;
    }

    public Set<Location> getLocations() {
        return locations;
    }

    private void setNom(String nom) {
        this.nom = nom;
    }

    private void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    private void setDateN(Date dateN) {
        this.dateN = dateN;
    }

    private void setSexe(Sexe sexe) {
        this.sexe = sexe;
    }

    private void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    private void setDateDebutAb(Date dateDebutAb) {
        this.dateDebutAb = dateDebutAb;
    }

    private void setCreditTemps(Integer creditTemps) {
        this.creditTemps = creditTemps;
    }

    public void linkLocations(Location _locations) {
        if (_locations != null) {
            _locations.unlinkAbonne();
            _locations.setAbonne(this);
            getLocations().add(_locations);
        }
    }

    public void unlinkLocations(Location _locations) {
        if (_locations != null) {
            _locations.setAbonne(null);
            getLocations().remove(_locations);
        }
    }

    public void unlinkLocations(Location _locations, Iterator<Location> it) {
        if (_locations != null) {
            _locations.setAbonne(null);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF/ZH1uig1SsOU= >>
// ----------- >>
}or<Location> it) {
        if (_locations != null) {
            _locations.setAbonne(null);
            it.remove();
        }
        return this;
    }

// ----------- << class.extras@AAAAAAF/ZH1uig1SsOU= >>
// ----------- >>
}