/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF/ZGknpANNGXQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF/ZGknpANNGXQ= >>
// ----------- >>
public class Bornette {
    // ----------- << attribute.annotations@AAAAAAF/ZGlhfAN4Rpw= >>
    // ----------- >>
    private Etat etat;

    // ----------- << attribute.annotations@AAAAAAF/ZG/yygTvJRE= >>
    // ----------- >>
    private Station station;

    // ----------- << attribute.annotations@AAAAAAF/ZHFw1QVdHxk= >>
    // ----------- >>
    private Velo velo;

    private Etat getEtat() {
        return etat;
    }

    public Station getStation() {
        return station;
    }

    public Velo getVelo() {
        return velo;
    }

    private void setEtat(Etat etat) {
        this.etat = etat;
    }

    public void setStation(Station station) {
        this.station = station;
    }

    public void setVelo(Velo velo) {
        this.velo = velo;
    }

    public void linkStation(Station _station) {
        if (_station != null) {
            _station.getBornettes().add(this);
        }

        unlinkStation();
        setStation(_station);
    }

    public void linkVelo(Velo _velo) {
        if (_velo != null) {
            _velo.unlinkBornette();
            _velo.setBornette(this);
        }

        unlinkVelo();
        setVelo(_velo);
    }

    public void unlinkStation() {
        if (getStation() != null) {
            getStation().getBornettes().remove(this);
            setStation(null);
        }
    }

    public void unlinkVelo() {
        if (getVelo() != null) {
            getVelo().setBornette(null);
            setVelo(null);
        }
    }

// ----------- << class.extras@AAAAAAF/ZGknpANNGXQ= >>
// ----------- >>
}       getVelo().setBornette(null);
            setVelo(null);
        }
        return this;
    }

// ----------- << class.extras@AAAAAAF/ZGknpANNGXQ= >>
// ----------- >>
}