/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF/iJT5CfHGNu4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF/iJT5CfHGNu4= >>
// ----------- >>
public class Client {
    // ----------- << attribute.annotations@AAAAAAF/iJlhTgPr9uw= >>
    // ----------- >>
    private Integer numeroCB;

    // ----------- << attribute.annotations@AAAAAAF/iJuDiAXHrJM= >>
    // ----------- >>
    private String codeSecret;

    private Integer getNumeroCB() {
        return numeroCB;
    }

    private String getCodeSecret() {
        return codeSecret;
    }

    private void setNumeroCB(Integer numeroCB) {
        this.numeroCB = numeroCB;
    }

    private void setCodeSecret(String codeSecret) {
        this.codeSecret = codeSecret;
    }

// ----------- << class.extras@AAAAAAF/iJT5CfHGNu4= >>
// ----------- >>
}as@AAAAAAF/iJT5CfHGNu4= >>
// ----------- >>
}