/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF/ZND+EUPm26g= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF/ZND+EUPm26g= >>
// ----------- >>
public enum Definition {
    vplus,
    vmoins,
    vnul;

// ----------- << enum.extras@AAAAAAF/ZND+EUPm26g= >>
// ----------- >>
}