/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF/ZJfabxq9WsA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF/ZJfabxq9WsA= >>
// ----------- >>
public class Location {
    // ----------- << attribute.annotations@AAAAAAF/ZJlPXR1kuPk= >>
    // ----------- >>
    private Integer dureeLoc;

    // ----------- << attribute.annotations@AAAAAAF/ZKF6IiJtfv8= >>
    // ----------- >>
    private Float prix;

    // ----------- << attribute.annotations@AAAAAAF/ZLLZeS+R3Jw= >>
    // ----------- >>
    private Set<Trajet> velos = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF/ZONRumSql1Y= >>
    // ----------- >>
    private Abonne abonne;

    // ----------- << attribute.annotations@AAAAAAF/ZOUfgGl/ahs= >>
    // ----------- >>
    private NonAbonne nonAbonne;

    private Integer getDureeLoc() {
        return dureeLoc;
    }

    private Float getPrix() {
        return prix;
    }

    public Set<Trajet> getVelos() {
        return velos;
    }

    public Abonne getAbonne() {
        return abonne;
    }

    public NonAbonne getNonAbonne() {
        return nonAbonne;
    }

    private void setDureeLoc(Integer dureeLoc) {
        this.dureeLoc = dureeLoc;
    }

    private void setPrix(Float prix) {
        this.prix = prix;
    }

    public void setAbonne(Abonne abonne) {
        this.abonne = abonne;
    }

    public void setNonAbonne(NonAbonne nonAbonne) {
        this.nonAbonne = nonAbonne;
    }

    public void linkVelos(Trajet _velos) {
        if (_velos != null) {
            _velos.unlinkLocationVelo();
            _velos.setLocationVelo(this);
            getVelos().add(_velos);
        }
    }

    public void linkAbonne(Abonne _abonne) {
        if (_abonne != null) {
            _abonne.getLocations().add(this);
        }

        unlinkAbonne();
        setAbonne(_abonne);
    }

    public void linkNonAbonne(NonAbonne _nonAbonne) {
        if (_nonAbonne != null) {
            _nonAbonne.getLocationsNonAbos().add(this);
        }

        unlinkNonAbonne();
        setNonAbonne(_nonAbonne);
    }

    public void unlinkVelos(Trajet _velos) {
        if (_velos != null) {
            _velos.setLocationVelo(null);
            getVelos().remove(_velos);
        }
    }

    public void unlinkVelos(Trajet _velos, Iterator<Trajet> it) {
        if (_velos != null) {
            _velos.setLocationVelo(null);
            it.remove();
        }
    }

    public void unlinkAbonne() {
        if (getAbonne() != null) {
            getAbonne().getLocations().remove(this);
            setAbonne(null);
        }
    }

    public void unlinkNonAbonne() {
        if (getNonAbonne() != null) {
            getNonAbonne().getLocationsNonAbos().remove(this);
            setNonAbonne(null);
        }
    }


    // ----------- << method.annotations@AAAAAAF/ZKD3byFqop4= >>
    // ----------- >>
    public Double calculPrix() {
    // ----------- << method.body@AAAAAAF/ZKD3byFqop4= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF/ZJfabxq9WsA= >>
// ----------- >>
}/ ----------- << method.annotations@AAAAAAF/ZKD3byFqop4= >>
    // ----------- >>
    public Double calculPrix() {
    // ----------- << method.body@AAAAAAF/ZKD3byFqop4= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF/ZJfabxq9WsA= >>
// ----------- >>
}