/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF/ZN8ej1PRBuk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF/ZN8ej1PRBuk= >>
// ----------- >>
public class NonAbonne extends Client {
    // ----------- << attribute.annotations@AAAAAAF/ZOUfgWmAwfE= >>
    // ----------- >>
    private Set<Location> locationsNonAbos = new HashSet<>();

    public Set<Location> getLocationsNonAbos() {
        return locationsNonAbos;
    }

    public void linkLocationsNonAbos(Location _locationsNonAbos) {
        if (_locationsNonAbos != null) {
            _locationsNonAbos.unlinkNonAbonne();
            _locationsNonAbos.setNonAbonne(this);
            getLocationsNonAbos().add(_locationsNonAbos);
        }
    }

    public void unlinkLocationsNonAbos(Location _locationsNonAbos) {
        if (_locationsNonAbos != null) {
            _locationsNonAbos.setNonAbonne(null);
            getLocationsNonAbos().remove(_locationsNonAbos);
        }
    }

    public void unlinkLocationsNonAbos(Location _locationsNonAbos, Iterator<Location> it) {
        if (_locationsNonAbos != null) {
            _locationsNonAbos.setNonAbonne(null);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF/ZN8ej1PRBuk= >>
// ----------- >>
} }

// ----------- << class.extras@AAAAAAF/ZN8ej1PRBuk= >>
// ----------- >>
}