/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF1ejkD4MSTsIs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF1ejkD4MSTsIs= >>
// ----------- >>
public class Station {
    // ----------- << attribute.annotations@AAAAAAF/ZGcjYAKPvpk= >>
    // ----------- >>
    private String adresse;

    // ----------- << attribute.annotations@AAAAAAF/ZG/yygTwRvo= >>
    // ----------- >>
    private Set<Bornette> bornettes = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF/iMSFj3DOemA= >>
    // ----------- >>
    private Set<Trajet> debutTrajets = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF/iMTHnXGW/I0= >>
    // ----------- >>
    private Set<Trajet> finTrajets = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF/iOb3VusHR2A= >>
    // ----------- >>
    private Set<DefinitionStation> definitions = new HashSet<>();

    private String getAdresse() {
        return adresse;
    }

    public Set<Bornette> getBornettes() {
        return bornettes;
    }

    public Set<Trajet> getDebutTrajets() {
        return debutTrajets;
    }

    public Set<Trajet> getFinTrajets() {
        return finTrajets;
    }

    public Set<DefinitionStation> getDefinitions() {
        return definitions;
    }

    private void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public void linkBornettes(Bornette _bornettes) {
        if (_bornettes != null) {
            _bornettes.unlinkStation();
            _bornettes.setStation(this);
            getBornettes().add(_bornettes);
        }
    }

    public void linkDebutTrajets(Trajet _debutTrajets) {
        if (_debutTrajets != null) {
            _debutTrajets.unlinkStationDepart();
            _debutTrajets.setStationDepart(this);
            getDebutTrajets().add(_debutTrajets);
        }
    }

    public void linkFinTrajets(Trajet _finTrajets) {
        if (_finTrajets != null) {
            _finTrajets.unlinkStationArrive();
            _finTrajets.setStationArrive(this);
            getFinTrajets().add(_finTrajets);
        }
    }

    public void linkDefinitions(DefinitionStation _definitions) {
        if (_definitions != null) {
            _definitions.unlinkStation();
            _definitions.setStation(this);
            getDefinitions().add(_definitions);
        }
    }

    public void unlinkBornettes(Bornette _bornettes) {
        if (_bornettes != null) {
            _bornettes.setStation(null);
            getBornettes().remove(_bornettes);
        }
    }

    public void unlinkBornettes(Bornette _bornettes, Iterator<Bornette> it) {
        if (_bornettes != null) {
            _bornettes.setStation(null);
            it.remove();
        }
    }

    public void unlinkDebutTrajets(Trajet _debutTrajets) {
        if (_debutTrajets != null) {
            _debutTrajets.setStationDepart(null);
            getDebutTrajets().remove(_debutTrajets);
        }
    }

    public void unlinkDebutTrajets(Trajet _debutTrajets, Iterator<Trajet> it) {
        if (_debutTrajets != null) {
            _debutTrajets.setStationDepart(null);
            it.remove();
        }
    }

    public void unlinkFinTrajets(Trajet _finTrajets) {
        if (_finTrajets != null) {
            _finTrajets.setStationArrive(null);
            getFinTrajets().remove(_finTrajets);
        }
    }

    public void unlinkFinTrajets(Trajet _finTrajets, Iterator<Trajet> it) {
        if (_finTrajets != null) {
            _finTrajets.setStationArrive(null);
            it.remove();
        }
    }

    public void unlinkDefinitions(DefinitionStation _definitions) {
        if (_definitions != null) {
            _definitions.setStation(null);
            getDefinitions().remove(_definitions);
        }
    }

    public void unlinkDefinitions(DefinitionStation _definitions, Iterator<DefinitionStation> it) {
        if (_definitions != null) {
            _definitions.setStation(null);
            it.remove();
        }
    }


    // ----------- << method.annotations@AAAAAAF/ZMJ1yjzYtg0= >>
    // ----------- >>
    public String getAdresse() {
    // ----------- << method.body@AAAAAAF/ZMJ1yjzYtg0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF1ejkD4MSTsIs= >>
// ----------- >>
} }
        return this;
    }


    // ----------- << method.annotations@AAAAAAF/ZMJ1yjzYtg0= >>
    // ----------- >>
    public String getAdresse() {
    // ----------- << method.body@AAAAAAF/ZMJ1yjzYtg0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF1ejkD4MSTsIs= >>
// ----------- >>
}