/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF/iLVnLkYNJME= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF/iLVnLkYNJME= >>
// ----------- >>
public class Trajet {
    // ----------- << attribute.annotations@AAAAAAF/iLYAiEeQQBc= >>
    // ----------- >>
    private Date dateDebutTrajet;

    // ----------- << attribute.annotations@AAAAAAF/iLb200kAJcQ= >>
    // ----------- >>
    private Date dateFinTrajet;

    // ----------- << attribute.annotations@AAAAAAF/iLd3m0pxcnI= >>
    // ----------- >>
    private Integer duree;

    // ----------- << attribute.annotations@AAAAAAF/iLkihUt1FaI= >>
    // ----------- >>
    private Real prix;

    // ----------- << attribute.annotations@AAAAAAF/iMSFj3DNUts= >>
    // ----------- >>
    private Station stationDepart;

    // ----------- << attribute.annotations@AAAAAAF/iMTHnXGVph8= >>
    // ----------- >>
    private Station stationArrive;

    // ----------- << attribute.annotations@AAAAAAF/ZLLZeS+Q0sk= >>
    // ----------- >>
    private Location locationVelo;

    // ----------- << attribute.annotations@AAAAAAF/iNGpv6nEw5c= >>
    // ----------- >>
    private Velo velo;

    public Date getDateDebutTrajet() {
        return dateDebutTrajet;
    }

    public Date getDateFinTrajet() {
        return dateFinTrajet;
    }

    public Integer getDuree() {
        return duree;
    }

    public Real getPrix() {
        return prix;
    }

    public Station getStationDepart() {
        return stationDepart;
    }

    public Station getStationArrive() {
        return stationArrive;
    }

    public Location getLocationVelo() {
        return locationVelo;
    }

    public Velo getVelo() {
        return velo;
    }

    public void setDateDebutTrajet(Date dateDebutTrajet) {
        this.dateDebutTrajet = dateDebutTrajet;
    }

    public void setDateFinTrajet(Date dateFinTrajet) {
        this.dateFinTrajet = dateFinTrajet;
    }

    public void setDuree(Integer duree) {
        this.duree = duree;
    }

    public void setPrix(Real prix) {
        this.prix = prix;
    }

    public void setStationDepart(Station stationDepart) {
        this.stationDepart = stationDepart;
    }

    public void setStationArrive(Station stationArrive) {
        this.stationArrive = stationArrive;
    }

    public void setLocationVelo(Location locationVelo) {
        this.locationVelo = locationVelo;
    }

    public void setVelo(Velo velo) {
        this.velo = velo;
    }

    public void linkStationDepart(Station _stationDepart) {
        if (_stationDepart != null) {
            _stationDepart.getDebutTrajets().add(this);
        }

        unlinkStationDepart();
        setStationDepart(_stationDepart);
    }

    public void linkStationArrive(Station _stationArrive) {
        if (_stationArrive != null) {
            _stationArrive.getFinTrajets().add(this);
        }

        unlinkStationArrive();
        setStationArrive(_stationArrive);
    }

    public void linkLocationVelo(Location _locationVelo) {
        if (_locationVelo != null) {
            _locationVelo.getVelos().add(this);
        }

        unlinkLocationVelo();
        setLocationVelo(_locationVelo);
    }

    public void linkVelo(Velo _velo) {
        if (_velo != null) {
            _velo.getTrajets().add(this);
        }

        unlinkVelo();
        setVelo(_velo);
    }

    public void unlinkStationDepart() {
        if (getStationDepart() != null) {
            getStationDepart().getDebutTrajets().remove(this);
            setStationDepart(null);
        }
    }

    public void unlinkStationArrive() {
        if (getStationArrive() != null) {
            getStationArrive().getFinTrajets().remove(this);
            setStationArrive(null);
        }
    }

    public void unlinkLocationVelo() {
        if (getLocationVelo() != null) {
            getLocationVelo().getVelos().remove(this);
            setLocationVelo(null);
        }
    }

    public void unlinkVelo() {
        if (getVelo() != null) {
            getVelo().getTrajets().remove(this);
            setVelo(null);
        }
    }


    // ----------- << method.annotations@AAAAAAF/iLn2H1K/Yvo= >>
    // ----------- >>
    public void CalculPrixTrajet() {
    // ----------- << method.body@AAAAAAF/iLn2H1K/Yvo= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF/iLVnLkYNJME= >>
// ----------- >>
}jets().remove(this);
            setVelo(null);
        }
        return this;
    }


    // ----------- << method.annotations@AAAAAAF/iLn2H1K/Yvo= >>
    // ----------- >>
    public void CalculPrixTrajet() {
    // ----------- << method.body@AAAAAAF/iLn2H1K/Yvo= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF/iLVnLkYNJME= >>
// ----------- >>
}